name: microservices_build
on:
  - push
  - pull_request
jobs:
  build_api:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_outputs.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t myorg/api:${{ github.sha }} ./services/api
      - run: echo image_tag=myorg/api:${{ github.sha }} >> $GITHUB_OUTPUT
  build_web:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_outputs.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t myorg/web:${{ github.sha }} ./services/web
      - run: echo image_tag=myorg/web:${{ github.sha }} >> $GITHUB_OUTPUT
  build_worker:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_outputs.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t myorg/worker:${{ github.sha }} ./services/worker
      - run: echo image_tag=myorg/worker:${{ github.sha }} >> $GITHUB_OUTPUT
  build_gateway:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_outputs.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t myorg/gateway:${{ github.sha }} ./services/gateway
      - run: echo image_tag=myorg/gateway:${{ github.sha }} >> $GITHUB_OUTPUT
  test_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd services/api && npm ci && npm run test:unit
  test_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd services/web && npm ci && npm run test:unit
  test_worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd services/worker && npm ci && npm run test:unit
  test_gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd services/gateway && npm ci && npm run test:unit
  integration_tests:
    runs-on: ubuntu-latest
    needs:
      - build_api
      - build_web
      - build_worker
      - build_gateway
      - test_api
      - test_web
      - test_worker
      - test_gateway
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f docker-compose.test.yml up -d
      - run: sleep 30
      - run: npm run test:integration
      - run: docker-compose -f docker-compose.test.yml down
  contract_tests:
    runs-on: ubuntu-latest
    needs:
      - build_api
      - build_web
      - build_worker
      - build_gateway
    steps:
      - uses: actions/checkout@v4
      - run: npm run test:contracts
  e2e_tests:
    runs-on: ubuntu-latest
    needs:
      - integration_tests
      - contract_tests
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f docker-compose.e2e.yml up -d
      - run: npx playwright test
      - run: docker-compose -f docker-compose.e2e.yml down
  publish_images:
    runs-on: ubuntu-latest
    needs:
      - e2e_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo Publishing all service images to ghcr.io
  notify_completion:
    runs-on: ubuntu-latest
    needs:
      - e2e_tests
    steps:
      - run: echo Build pipeline completed

