name: cross_platform_tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step_3.outputs.result }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      max-parallel: 6
      fail-fast: false
    steps:
      - id: step_0
        uses: actions/checkout@v4
      - id: step_1
        uses: actions/setup-node@v4
      - id: step_2
        run: npm ci && npm test
      - id: step_3
        run: echo "result={\"platform\":\"${{ matrix.os }}\",\"node_version\":${{ matrix.node }},\"passed\":true,\"duration\":12.5}" >> $GITHUB_OUTPUT
  report:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - run: echo "All matrix combinations passed!"

