name: multi_reviewer
on:
  workflow_dispatch:
    inputs:
      review:
        description: Current iteration phase for cycle review_cycle
        required: false
        default: "0"
      run_id:
        description: Run ID for artifact retrieval
        required: false
        default: ""
concurrency:
  group: ${{ inputs._cycle_key || 'review' }}
  cancel-in-progress: false
jobs:
  finalize:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Review cycle complete!"
  review_cycle_hydrate:
    runs-on: ubuntu-latest
    outputs:
      phase: ${{ steps.init_state.outputs.phase }}
    steps:
      - name: Download cycle state
        uses: actions/download-artifact@v4
        if: github.event.inputs.review != '0' && github.event.inputs.review != ''
        with:
          name: review_cycle-state
          path: .cycle-state
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Initialize cycle state
        id: init_state
        run: |-
          PHASE=${{ github.event.inputs.review || '0' }}
          if [ -f .cycle-state/state.json ]; then
            echo "Loaded state from artifact"
            cat .cycle-state/state.json
          else
            echo '{"review": '$PHASE'}' > state.json
            mkdir -p .cycle-state
            cp state.json .cycle-state/state.json
          fi
          echo "phase=$PHASE" >> $GITHUB_OUTPUT
        shell: bash
  review_cycle_body_reviewer_clarity:
    runs-on: ubuntu-latest
    needs:
      - review_cycle_hydrate
    steps:
      - uses: actions/checkout@v4
      - name: reviewer_clarity-task
        uses: anthropics/claude-code-action@v1
        with:
          prompt: Review code for clarity and readability
          allowed_tools: '["Read","Glob"]'
          max_turns: 3
          model: claude-sonnet-4-20250514
      - name: Upload review-clarity
        uses: actions/upload-artifact@v4
        with:
          name: review-clarity
          path: review-clarity
  review_cycle_body_reviewer_security:
    runs-on: ubuntu-latest
    needs:
      - review_cycle_hydrate
    steps:
      - uses: actions/checkout@v4
      - name: reviewer_security-task
        uses: anthropics/claude-code-action@v1
        with:
          prompt: Review code for security issues
          allowed_tools: '["Read","Glob","Grep"]'
          max_turns: 3
          model: claude-sonnet-4-20250514
      - name: Upload review-security
        uses: actions/upload-artifact@v4
        with:
          name: review-security
          path: review-security
  review_cycle_body_aggregate:
    runs-on: ubuntu-latest
    needs:
      - review_cycle_hydrate
      - review_cycle_body_reviewer_clarity
      - review_cycle_body_reviewer_security
    outputs:
      result: ${{ steps.step_0.outputs.result }}
    steps:
      - id: step_0
        run: |-
          echo "Aggregating reviews..."
          echo "result={\"average_score\":4,\"consensus_reached\":true}" >> $GITHUB_OUTPUT
  review_cycle_decide:
    runs-on: ubuntu-latest
    needs:
      - review_cycle_body_aggregate
    outputs:
      continue: ${{ steps.eval_guard.outputs.continue }}
      termination_reason: ${{ steps.eval_guard.outputs.termination_reason }}
    steps:
      - name: Evaluate guard condition
        id: eval_guard
        run: |-
          node -e "const fs = require('fs'); let state = {}; if (fs.existsSync('.cycle-state/state.json')) {   state = JSON.parse(fs.readFileSync('.cycle-state/state.json', 'utf8')); } const phase = parseInt(process.env.PHASE || '0', 10); const maxIters = 3; const context = { ...state, review: phase }; const guardResult = (function() {        return state.iteration >= 2;      })(); console.log('Guard result:', guardResult); let terminationReason = 'continue'; let shouldContinue = true; if (guardResult) {   terminationReason = 'guard_satisfied';   shouldContinue = false; } else if (maxIters !== null && phase >= maxIters - 1) {   terminationReason = 'max_iterations';   shouldContinue = false; } console.log('Termination reason:', terminationReason); fs.writeFileSync('.cycle-state/continue.txt', shouldContinue ? 'true' : 'false'); fs.writeFileSync('.cycle-state/termination_reason.txt', terminationReason); fs.writeFileSync('.cycle-state/state.json', JSON.stringify({ ...context, quality_score: context.quality_score || 0 }));"
          CONTINUE=$(cat .cycle-state/continue.txt)
          TERMINATION_REASON=$(cat .cycle-state/termination_reason.txt)
          echo "continue=$CONTINUE" >> $GITHUB_OUTPUT
          echo "termination_reason=$TERMINATION_REASON" >> $GITHUB_OUTPUT
        shell: bash
        env:
          PHASE: ${{ needs.review_cycle_hydrate.outputs.phase }}
      - name: Upload cycle state
        uses: actions/upload-artifact@v4
        with:
          name: review_cycle-state
          path: .cycle-state
  review_cycle_dispatch:
    runs-on: ubuntu-latest
    needs:
      - review_cycle_decide
      - review_cycle_hydrate
    if: needs.review_cycle_decide.outputs.continue == 'true' && ${{ needs.review_cycle_hydrate.outputs.phase }} < 3
    steps:
      - name: Dispatch next iteration
        run: |-
          NEXT_PHASE=$(( ${{ needs.review_cycle_hydrate.outputs.phase }} + 1 ))
          gh workflow run "${{ github.workflow }}" \
            --ref "${{ github.ref }}" \
            -f review=$NEXT_PHASE \
            -f run_id=${{ github.run_id }}
          echo "Dispatched iteration $NEXT_PHASE"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

