name: agent_demo
on: workflow_dispatch
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: review-task
        uses: anthropics/claude-code-action@v1
        with:
          prompt: Review the codebase and provide feedback
          allowed_tools: '["Read","Glob","Grep"]'
          max_turns: 5
          model: claude-sonnet-4-20250514
      - name: Upload review_result
        uses: actions/upload-artifact@v4
        with:
          name: review_result
          path: review_result

