name: typed_pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.set_outputs.outputs.info }}
    steps:
      - uses: actions/checkout@v4
      - run: |-
          VERSION=$(cat package.json | jq -r .version)
          COMMIT=${{ github.sha }}
          TIMESTAMP=$(date +%s)
          echo "info={\"version\":\"$VERSION\",\"commit\":\"$COMMIT\",\"timestamp\":$TIMESTAMP,\"success\":true}" >> $GITHUB_OUTPUT
  review:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: review-task
        uses: anthropics/claude-code-action@v1
        with:
          prompt: Review the code changes and provide structured feedback
          allowed_tools: '["Read","Glob","Grep"]'
          max_turns: 5
          model: claude-sonnet-4-20250514
          output_schema:
            type: object
            properties:
              approved:
                type: boolean
              rating:
                type: integer
              comments:
                type: array
                items:
                  type: object
                  properties:
                    filepath:
                      type: string
                    line:
                      type: integer
                    severity:
                      type: string
                    message:
                      type: string
                  required:
                    - filepath
                    - line
                    - severity
                    - message
                  additionalProperties: false
            required:
              - approved
              - rating
              - comments
            additionalProperties: false
      - name: Upload review_result
        uses: actions/upload-artifact@v4
        with:
          name: review_result
          path: review_result
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - review
    steps:
      - run: "echo Deploying version: ${{ fromJSON(needs.build.outputs.info).version }}"
      - run: "echo Commit: ${{ fromJSON(needs.build.outputs.info).commit }}"
      - run: "echo Build timestamp: ${{ fromJSON(needs.build.outputs.info).timestamp }}"

