name: guard_job_example
on: issues
jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      check_labels_result: ${{ steps.check_labels.outputs.result }}
    steps:
      - name: Evaluate guard
        id: check_labels
        run: "node -e \"const fs = require('fs'); const context = {   event: JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')),   ref: process.env.GITHUB_REF,   inputs: JSON.parse(process.env.INPUTS || '{}') }; const result = (function() {          const labels = context.event.issue?.labels || [];         const hasPriority = labels.some(l => l.name === 'priority');         const isOpen = context.event.action === 'opened';         return hasPriority && isOpen;        })(); console.log('Guard result:', result); fs.appendFileSync(process.env.GITHUB_OUTPUT, 'result=' + result + '\\n');\""
        shell: bash
        env:
          INPUTS: ${{ toJson(inputs) }}
  process:
    runs-on: ubuntu-latest
    needs:
      - guard
    steps:
      - run: echo Processing priority issue...
      - run: npm run process-issue

