name: guard_job_example
on: issues
jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      check_labels_result: ${{ steps.check_labels.outputs.result }}
    steps:
      - name: Evaluate guard
        id: check_labels
        run: "node -e \"const fs = require('fs'); const context = {   event: JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')),   ref: process.env.GITHUB_REF,   inputs: JSON.parse(process.env.INPUTS || '{}') }; const guards = {   get event() { return context.event; },   get ref() { return context.ref; },   get inputs() { return context.inputs; },   get actor() { return context.event?.sender?.login || ''; },   hasLabel(name) {     const labels = context.event?.issue?.labels || context.event?.pull_request?.labels || [];     return labels.some(l => l.name === name);   },   hasAnyLabel(...names) {     return names.some(n => this.hasLabel(n));   },   hasAllLabels(...names) {     return names.every(n => this.hasLabel(n));   },   isBranch(name) {     return context.ref === 'refs/heads/' + name;   },   isDefaultBranch() {     return this.isBranch(context.event?.repository?.default_branch || 'main');   },   isPullRequest() {     return !!context.event?.pull_request;   },   isIssue() {     return !!context.event?.issue && !context.event?.pull_request;   },   isDraft() {     return context.event?.pull_request?.draft === true;   },   isAction(action) {     return context.event?.action === action;   } }; const result = (function() {          const labels = context.event.issue?.labels || [];         const hasPriority = labels.some(l => l.name === 'priority');         const isOpen = context.event.action === 'opened';         return hasPriority && isOpen;        })(); console.log('Guard result:', result); fs.appendFileSync(process.env.GITHUB_OUTPUT, 'result=' + result + '\\n');\""
        shell: bash
        env:
          INPUTS: ${{ toJson(inputs) }}
  process:
    runs-on: ubuntu-latest
    needs:
      - guard
    steps:
      - run: echo Processing priority issue...
      - run: npm run process-issue

