name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.set_outputs.outputs.info }}
    steps:
      - uses: actions/checkout@v4
      - run: VERSION=$(cat package.json | jq -r .version)
      - run: echo "info={\"version\":\"$VERSION\",\"commit\":\"${{ github.sha }}\",\"timestamp\":$(date +%s)}" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      result: ${{ steps.set_outputs.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - run: |-
          npm ci
          npm test -- --coverage
      - run: echo "result={\"passed\":true,\"coverage\":85.5,\"failed_count\":0}" >> $GITHUB_OUTPUT
  report:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - run: "echo Build version: ${{ fromJSON(needs.build.outputs.info).version }}"
      - run: "echo Test coverage: ${{ fromJSON(needs.test.outputs.result).coverage }}%"

