name: json_outputs
on: push
jobs:
  gather_info:
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.set_outputs.outputs.build_info }}
      deploy_config: ${{ steps.set_outputs.outputs.deploy_config }}
    steps:
      - run: echo "build_info={\"version\":\"2.1.0\",\"commit\":\"${{ github.sha }}\"}" >> $GITHUB_OUTPUT
      - run: echo "deploy_config={\"env\":\"staging\",\"replicas\":3}" >> $GITHUB_OUTPUT
  process_info:
    runs-on: ubuntu-latest
    needs:
      - gather_info
    steps:
      - run: "echo Build version: ${{ fromJSON(needs.gather_info.outputs.build_info).version }}"
      - run: "echo Deploy env: ${{ fromJSON(needs.gather_info.outputs.deploy_config).env }}"
      - run: "echo Replicas: ${{ fromJSON(needs.gather_info.outputs.deploy_config).replicas }}"

